In [2]:
# import dependencies
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

In [3]:
# get the html file using request
url = 'https://www.vlr.gg/91583/akrew-vs-100-thieves-knights-circuit-monthly-2022-april-ro16/?game=all&tab=overview'
html_txt = requests.get(url)
soup = BeautifulSoup(html_txt.text, 'lxml')
# get the match_stats
game_stats = soup.find('div', class_="vm-stats-container")
table_info = game_stats.find('table', class_='wf-table-inset mod-overview')

In [25]:
# get all the player names and team abreviation
body = table_info.find('tbody')
tr = body.find_all('tr')

# create a variable to hold our webscraped info
a = []

# use a while loop to access each players info and send it into the list
x=0
while x < len(tr):
    trx = tr[x]
    td_name = trx.find('td', class_='mod-player')
    div = td_name.find('div')
    a.append(div.find('a'))
    x+=1

# create lists to hold each string of information
name_web=[]
team_web=[]

# use a while loop to find the info that we need and put it into the lists
i=0
while i < len(a):
    ai = a[i]
    name_web.append(ai.find('div', class_='text-of').text)
    team_web.append(ai.find('div', class_='ge-text-light').text)
    i+=1

# create our final variables to hold the player information
name = []
team = []
team_close = []
p = '\n\t*'
p1 = '\t*'
for n in name_web:
    name.append(re.sub(p, '', n))


for n in team_web:
    team_close.append(re.sub(p, '', n))
for b in team_close:
    team.append(re.sub(p1, '', b))
print(name)
print(team)

['jovahnii ', 'ZachaREEE ', 'Neon ', 'Paincakes ', 'gucc107 ']
['Akre', 'Akre', 'Akre', 'Akre', 'Akre']

In [37]:
# mapping to the correct location for all player for acs, kills, deaths, etc.
body = table_info.find('tbody')
tr = body.find_all('tr')

# create lists to hold the data
acs_both = []
acs_t = []
acs_ct = []

# use a while loop to get to the information for each player and add it into our lists
x=0
while x < len(tr):
    trx = tr[x]
    td_stat = trx.find('td', class_='mod-stat')
    span_sq = td_stat.find('span', class_='stats-sq')
    acs_both.append(span_sq.find('span', class_='side mod-side mod-both').text)
    acs_t.append(span_sq.find('span', class_='side mod-side mod-t').text)
    acs_ct.append(span_sq.find('span', class_='side mod-side mod-ct').text)
    x+=1

# set all the list data into integers
acs_both = list(map(int, acs_both))
acs_t = list(map(int, acs_t))
acs_ct = list(map(int, acs_ct))

# print to double check I am right
print(acs_both)
print(acs_t)
print(acs_ct)

[265, 191, 189, 186, 142]
[202, 153, 192, 125, 203]
[314, 220, 188, 232, 97]

In [39]:
# create a dictionary to hold all of the data
matches_dict = {
    'Player Name': name,
    'Team': team,
    'ACS Total': acs_both,
    'ACS Attack': acs_t,
    'ACS Defense': acs_ct,
    'Kill Total': 
    'Kill Attack':
    'Kill Defense':
    'Death Total':
    'Death Attack':
    'Death Defense':
    'Assist Total':
    'Assist Attack':
    'Assist Defense':
    'ADR':
    'First Kills':
    'First Deaths':
}

# create a df from the dictionary
matches_df = pd.DataFrame(matches_dict)
matches_df

  Player Name  Team  ACS Total  ACS Attack  ACS Defense
0   jovahnii   Akre        265         202          314
1  ZachaREEE   Akre        191         153          220
2       Neon   Akre        189         192          188
3  Paincakes   Akre        186         125          232
4    gucc107   Akre        142         203           97